//30*30
var ctx,fillcolor,canv,nextcvx;
//var time=450;
var time=250;
var nextfillcolor;

function drawnextBlock(x,y){
	nextcvx.fillStyle=nextfillcolor;
	nextcvx.fillRect(x,y,30,30);
	nextcvx.strokeRect(x,y,30,30);
}

function drawBlock(x,y){
	ctx.fillStyle=fillcolor;
	ctx.fillRect(x,y,30,30);
	ctx.strokeRect(x,y,30,30);
}

function tetoris(){
	canv=document.getElementById("nextblock");
	nextcvx=canv.getContext('2d');
	var tetoris=document.getElementById("tetoris");
	block=makeblock();
	fillcolor="skyblue";
	drawBlock(0,0);
	drawBlock(0,32);
	drawBlock(32,0);
	drawBlock(32,32);
	
		nextcvx.clearRect(0,0,100,100);
		nextfillcolor="red";
		drawnextBlock(0,0);
		drawnextBlock(0,32);
		drawnextBlock(0,64);
		drawnextBlock(32,64);
	
	//down block
	block.animate({
		"top":"+=62px",
		"left":"-=40px"
	},time)
	block.animate({
		"top":"+=62px",
		"left":"-=48px"
	},time)
	block.animate({
		"top":"+=62px"
	},time)
	block.animate({
		"top":"+=62px"
	},time)
	block.animate({
		"top":"+=62px"
	},time)
	block.animate({
		"top":"+=62px"
	},time)
	block.animate({
		"top":"+=62px"
	},time)
	block.animate({
		"top":"+=62px"
	},time)
	//end
	setTimeout(function(){
		block=makeblock();
		fillcolor="red";
		drawBlock(0,0);
		drawBlock(0,32);
		drawBlock(0,64);
		drawBlock(32,64);
			nextcvx.clearRect(0,0,100,100);
			nextfillcolor="skyblue";
			drawnextBlock(0,0);
			drawnextBlock(0,32);
			drawnextBlock(32,0);
			drawnextBlock(32,32);
		
		//down block
		block.animate({
			"top":"+=62px",
		"left":"-=40px"
		},time)
		block.animate({
			"top":"+=62px",
		"left":"-=48px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=30px"
		},time)
		//end
	},time*7+500);
	setTimeout(function(){
		block=makeblock();
		fillcolor="skyblue";
		drawBlock(0,0);
		drawBlock(0,32);
		drawBlock(32,0);
		drawBlock(32,32);
			nextcvx.clearRect(0,0,100,100);
			nextfillcolor="green";
			drawnextBlock(0,32);
			drawnextBlock(32,32);
			drawnextBlock(64,32);
			drawnextBlock(32,0);
		
		//down block
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px",
			"left":"-=25px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		//end
	},(time*7+500)*2)
	setTimeout(function(){
		block=makeblock();
		fillcolor="green";
		drawBlock(0,32);
		drawBlock(32,32);
		drawBlock(64,32);
		drawBlock(32,0);
			nextcvx.clearRect(0,0,100,100);
			nextfillcolor="yellow";
			drawnextBlock(0,0);
			drawnextBlock(0,32);
			drawnextBlock(0,64);
			drawnextBlock(0,96);
		
		//down block
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px",
			"left":"-=26px"
		},time)
		block.animate({
			"top":"+=62px"
			,"left":"-=30px"
		},time,function(){
			ctx.clearRect(0,0,100,100);
			drawBlock(32,0);
			drawBlock(32,32);
			drawBlock(32,64);
			drawBlock(0,32);
			}
		)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=30px"
		},time)
		//end
	},(time*7+500)*3);
		setTimeout(function(){
		block=makeblock();
		fillcolor="yellow";
		drawBlock(0,0);
		drawBlock(0,32);
		drawBlock(0,64);
		drawBlock(0,96);
			nextcvx.clearRect(0,0,100,100);
			nextfillcolor="yellow";
			drawnextBlock(0,0);
			drawnextBlock(0,32);
			drawnextBlock(0,64);
			drawnextBlock(0,96);
		
		//down block
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px",
			"left":"+=6px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		//end
	},(time*7+500)*4)
	setTimeout(function(){
		block=makeblock();
		fillcolor="yellow";
		drawBlock(0,0);
		drawBlock(0,32);
		drawBlock(0,64);
		drawBlock(0,96);
			nextcvx.clearRect(0,0,100,100);
			nextfillcolor="yellow";
			drawnextBlock(0,0);
			drawnextBlock(0,32);
			drawnextBlock(0,64);
			drawnextBlock(0,96);
		//down block
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px",
			"left":"+=6px"
		},time)
		block.animate({
			"top":"+=62px",
			"left":"+=30px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		//end
	},(time*7+500)*5)
	setTimeout(function(){
		block=makeblock();
		fillcolor="yellow";
		drawBlock(0,0);
		drawBlock(0,32);
		drawBlock(0,64);
		drawBlock(0,96);
			nextcvx.clearRect(0,0,100,100);
			nextfillcolor="yellow";
			drawnextBlock(0,0);
			drawnextBlock(0,32);
			drawnextBlock(0,64);
			drawnextBlock(0,96);
		//down block
		block.animate({
			"top":"+=62px",
				"left":"+=36px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px",
				"left":"+=30px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		//end
	},(time*7+500)*6)
	setTimeout(function(){
		block=makeblock();
		fillcolor="yellow";
		drawBlock(0,0);
		drawBlock(0,32);
		drawBlock(0,64);
		drawBlock(0,96);
			nextcvx.clearRect(0,0,100,100);
			nextfillcolor="yellow";
			drawnextBlock(0,0);
			drawnextBlock(0,32);
			drawnextBlock(0,64);
			drawnextBlock(0,96);
		//down block
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px",
				"left":"+=60px"
		},time)
		block.animate({
			"top":"+=62px",
				"left":"+=36px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		//end
	},(time*7+500)*7)
	setTimeout(function(){
		block=makeblock();
		fillcolor="yellow";
		drawBlock(0,0);
		drawBlock(0,32);
		drawBlock(0,64);
		drawBlock(0,96);
			nextcvx.clearRect(0,0,100,100);
			nextfillcolor="yellow";
			drawnextBlock(0,0);
			drawnextBlock(0,32);
			drawnextBlock(0,64);
			drawnextBlock(0,96);
		//down block
		block.animate({
			"top":"+=62px",
			"left":"60px"
		},time)
		block.animate({
			"top":"+=62px",
			"left":"+=36px"
		},time)
		block.animate({
			"top":"+=62px",
			"left":"+=70px"
		},time)
		block.animate({
			"top":"+=62px",
			"left":"+=60px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time,function(){
			var tetorisalert=$(document.createElement("div")).text("").css({
				"fontSize":"75px",
				"color":"red",
				"top":"424px",
				"width":"100px",
				"position":"relative",
				"width":"245px",
				"backgroundColor":"white",
				"textAlign":"center",
				"height":"125px"
			}).addClass("blocks");
			//$("#tetoris").append(tetorisalert);
			var bs=document.getElementsByClassName("blocks")			
			var i,cont;
			for(i=0;i<bs.length;i++){
				if(i==1||i==3||i==4){
					cont=bs[1].getContext('2d');
					cont.clearRect(0,30,100,100);
					cont=bs[3].getContext('2d');
					cont.clearRect(0,30,100,100);
					cont=bs[4].getContext('2d');
					cont.clearRect(0,60,100,100);
				}else{
					cont=bs[i].getContext('2d');
					cont.clearRect(0,0,100,160);
				}
				$(bs[i]).animate({
					top:"+=127px"
				},0)
			}
		}
		)
		//end
	},(time*7+500)*8)
		setTimeout(function(){
		block=makeblock();
		fillcolor="yellow";
		drawBlock(0,0);
		drawBlock(0,32);
		drawBlock(0,64);
		drawBlock(0,96);
			nextcvx.clearRect(0,0,100,100);
			nextfillcolor="yellow";
			drawnextBlock(0,0);
			drawnextBlock(0,32);
			drawnextBlock(0,64);
			drawnextBlock(0,96);
		//down block
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px",
			"left":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		//end
	},(time*7+500)*9)
	
	setTimeout(function(){
		block=makeblock();
		fillcolor="yellow";
		drawBlock(0,0);
		drawBlock(0,32);
		drawBlock(0,64);
		drawBlock(0,96);
			nextcvx.clearRect(0,0,100,100);
			nextfillcolor="yellow";
			drawnextBlock(0,0);
			drawnextBlock(0,32);
			drawnextBlock(0,64);
			drawnextBlock(0,96);
		//down block
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px",
			"left":"+=62px"
		},time)
		block.animate({
			"top":"+=62px",
			"left":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		//end
	},(time*7+500)*10)
	setTimeout(function(){
		block=makeblock();
		fillcolor="yellow";
		drawBlock(0,0);
		drawBlock(0,32);
		drawBlock(0,64);
		drawBlock(0,96);
			nextcvx.clearRect(0,0,100,100);
			nextfillcolor="yellow";
			drawnextBlock(0,0);
			drawnextBlock(0,32);
			drawnextBlock(0,64);
			drawnextBlock(0,96);
		//down block
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px",
			"left":"+=62px"
		},time)
		block.animate({
			"top":"+=62px",
			"left":"+=31px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		//end
	},(time*7+500)*11)
	setTimeout(function(){
		block=makeblock();
		fillcolor="yellow";
		drawBlock(0,0);
		drawBlock(0,32);
		drawBlock(0,64);
		drawBlock(0,96);
			nextcvx.clearRect(0,0,100,100);
			nextfillcolor="yellow";
			drawnextBlock(0,0);
			drawnextBlock(0,32);
			drawnextBlock(0,64);
			drawnextBlock(0,96);
		//down block
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px",
			"left":"+=32px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		//end
	},(time*7+500)*12)
	
	setTimeout(function(){
		block=makeblock();
		fillcolor="yellow";
		drawBlock(0,0);
		drawBlock(0,32);
		drawBlock(0,64);
		drawBlock(0,96);
			nextcvx.clearRect(0,0,100,100);
			nextfillcolor="yellow";
			drawnextBlock(0,0);
			drawnextBlock(0,32);
			drawnextBlock(0,64);
			drawnextBlock(0,96);
		//down block
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px",
			"left":"-=28px"
		},time)
		block.animate({
			"top":"+=62px",
			"left":"-=60px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=30px"
		},time)
		//end
	},(time*7+500)*13)
	
	setTimeout(function(){
		block=makeblock();
		fillcolor="yellow";
		drawBlock(0,0);
		drawBlock(0,32);
		drawBlock(0,64);
		drawBlock(0,96);
			nextcvx.clearRect(0,0,100,100);
			nextfillcolor="yellow";
			drawnextBlock(0,0);
			drawnextBlock(0,32);
			drawnextBlock(0,64);
			drawnextBlock(0,96);
		//down block
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px",
			"left":"-=25px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=30px"
		},time)
		//end
	},(time*7+500)*14)
	
		setTimeout(function(){
		block=makeblock();
		fillcolor="yellow";
		drawBlock(0,0);
		drawBlock(0,32);
		drawBlock(0,64);
		drawBlock(0,96);
			nextcvx.clearRect(0,0,100,100);
			nextfillcolor="yellow";
			drawnextBlock(0,0);
			drawnextBlock(0,32);
			drawnextBlock(0,64);
			drawnextBlock(0,96);
		//down block
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px",
			"left":"+=2px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		block.animate({
			"top":"+=62px"
		},time)
		//end
	},(time*7+500)*15)
	
}
function makeblock(){
	var block=document.createElement("canvas");
	$(block).css({
		position:"absolute",
		left:"100px"
	}).addClass("blocks");
	var canvas=block.getContext('2d');
	$("#tetoris").append($(block));
	ctx=canvas;
	return $(block);
}